Service kodajima
oyuki-prog/SuccessHoldingsTheme pull request #6
Opened 2022-10-13 15:03 UTC by yukodajima

serviceページ、ヘッダー部分を作成しました。確認お願いします。

2022-10-16 03:45 UTC, yukodajima commented
serviceページ、ヘッダー部分を修正しました。確認お願いします。

2022-10-16 04:58 UTC, oyuki-prog commented
@yukodajima 
全体的に、余白の大きさや、フォントサイズ、フォントカラーなどがカンプと違っている部分が見受けられます。
どのように実装したかのレビューをするのは、見栄えがほぼカンプ通りになってからにします。
全体を見直して、余白やフォントサイズ、フォントカラーはPC、SPともにカンプ通りになっているかを確認してください。
カンプ通りでない部分に関しては修正をお願いします。

2022-10-16 13:07 UTC, yukodajima commented
余白、フォントサイズ、フォントカラーを修正し、カンプ通りに出来たかと思います。
確認お願いします。

2022-10-16 13:37 UTC, oyuki-prog requested changes
最初に見せていただいたときよりかなりきれいにコーディングできていると思います！

全体的にfont-sizeをvwで指定していますが、画面幅が大きいと文字がやたらでかくなったり、画面幅が小さいと、文字がやたら小さくなったりしています。
SPでもフォントサイズが10pxとかでは小さくて見づらいので、割合による可変ではなく実数値でコーディングしましょう。

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  padding: 5% 5% 7%;
カンプで特に上下の余白については有意につけられている場合が多いです。
カンプでは上の余白が80px、下の余白が60pxなので
そのあたりは実数値でコーディングしましょう

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  font-size: 2.5vw;
フォントサイズについても、32pxと書いてあれば32pxでコーディングしましょう。
画面幅が極端に大きかったり小さかったりする際に表示が崩れる原因になります。
フォントサイズをvwで指定しているところが数カ所みられるので全体的に修正しましょう。

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  margin-top: 10%;
ここに関しても上の指摘と同様で実数値で問題ない部分です。
実数値だと困る部分と実数値で有るべき部分の区別がピンとこない場合は改めてお聞きください！

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  padding: 1vw;
こちらも実数値で行きましょう

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  margin-top: 10%;
こちらはカンプだと160pxの差があります。
現在上のブロックから下に80px
下のブロックから上に10%
で当たっています。
このままだと160pxではない余白ができているので実数値でコーディングしましょう。

2022-10-16 13:37 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +
画面幅650pxあたりから、ロゴとメニューが被っているので修正しましょう。

2022-10-16 13:37 UTC, oyuki-prog commented on html/service.html
> +              </p>
画像の場合を除き、divタグ内の子要素が一個だけ(ここではpタグのみ)の場合は、不要なdivがある可能性が高いです。p-article__textContainerがなくても実装できないか試してみてください。

2022-10-16 13:37 UTC, oyuki-prog commented on html/service.html
> +            <div>
ここのdivタグはなんのために付けられているでしょうか？
意図がなければ削除しましょう

2022-10-16 13:37 UTC, oyuki-prog commented on html/service.html
> +        <div class="p-header__imgContainer">
現状だと、画面幅が1400pxより大きいときに、ロゴとメニューが両端に表示され、視認性が悪くなっています。
headerも内部をl-containerで囲むことでコンテナーサイズが統一されるのでそのように実装しましょう。

2022-10-17 16:58 UTC, yukodajima commented
レビュー部分を修正しました。
確認お願いします。

2022-10-17 23:31 UTC, oyuki-prog commented
すみません、section間ならmarginで問題ないと思ったのですが、想定していた実装と違ったため、画面最下部の余白に背景色がついていないようです。
l-container と p-article をマルチクラスではなく別々に切り分け、その上でp-articleの上下に適切な余白を付ける形で対応してください。

昨日の確認事項としては
ヘッダー背景色問題は良さそうです！
Tab表示問題も良さそうです！
画像重ならない問題は解消されましたが、今度はコンテナサイズいっぱいではなくなってしまいました。
画像を大きくすることで解決できると思うので調整をお願いします。

上記は見栄えの段階なので、コードレビュー時にさらに修正頂く部分があるかもしれませんがご了承ください。

2022-10-18 03:43 UTC, yukodajima commented
>l-container と p-article をマルチクラスではなく別々に切り分け、その上でp-articleの上下に適切な余白を付ける形で対応してください。
l-container と p-article を別々に切り分けpadding-bottomを当てました。

>画像重ならない問題は解消されましたが、今度はコンテナサイズいっぱいではなくなってしまいました。
画像を大きくすることで解決できると思うので調整をお願いします。
デザインカンプは画像のサイズが指定されていたので、サイズは変えずに親要素にmax-width:1100pxをつけて画像が重なるようにし、且つコンテナサイズいっぱいし実装しました。
確認お願いします。

2022-10-18 09:07 UTC, oyuki-prog commented
下部のマージン問題
paddingで取れていてオッケーです。ですが現在の実装だと、l-containerに対し、p-articleは子要素なので上の余白もpaddingでつけましょう。

画像重ならない問題
画像は重なりましたが、l-containerにピッタリの幅ではなくなってしまったので、修正してください。

2022-10-18 12:41 UTC, yukodajima commented
余白調整しました。

画像重なり問題解決しました。

2022-10-18 13:32 UTC, oyuki-prog reviewed
見栄えはほぼ問題なさそうでしたので、コードレビューです！

フォントサイズに関しては、画面幅によって表示に違和感が生じない限りは基本的に実数値で問題は無いです。

余白の付け方に関しては、親子要素なのか、兄弟要素なのかを意識し、適切に適用できるようにしましょう。

メディアクエリを用いたレスポンシブ対応については、sp時のスタイルがpcを上書きする形であり、pcに当てたスタイルも基本的にはあたっているという認識を忘れていそうな部分があります。そこでずれが無いかをよく確認しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +            <img class="p-header__img" src="../assets/images/logo-sample.png" />
imgタグは一つのdivタグで囲むようにするので、pタグは外に出す形で実装しましょう。
(この先テキストも画像データでもらいますが、経験としてやっておきましょう。)

また、画像とテキストが含まれているのにimgContainerだとimgではないものが入っていることになるので、
logoWrapperクラス名が適切になるようにしましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +    </header>
無意味な改行は消しましょう

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +          <h2 class="p-hero__title">
「ヒーローヘッダー」とは、ウェブサイトのファーストビューに伝えたいメッセージ文言や、ナビゲーションメニューなどを全画面の画像や動画の上に配置したデザインのことをいいます。
参考リンク[https://mtame.jp/design/hero_header/](url)

今回は画像の上に配置したものではないため、heroという定義には当たりません。
より適切なクラス名に変えてみましょう。
(置換機能を使えば変更は一発でできます！)

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +                </p>
インデントが一個深くなっています。vscodeでは自動整形ツールなどもあるので、適宜利用しきれいな状態で提出しましょう。
参考リンク[https://mebee.info/2022/06/16/post-52119/](url)

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +              </div>
クラスがあたっていないdivタグ = styleがあたっていない = 不要なdivタグ
と考えて差し支えないです。

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +              <button class="p-article__btn c-btn" type="button">詳細</button>
インデント

2022-10-18 13:32 UTC, oyuki-prog commented on html/service.html
> +                </p>
インデント

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +    margin-top: 60px;
SP時、padding 160px と margin 60px が両方効いて220pxの余白ができています。不要な余白がつかないようにしましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_hero.scss
> +    margin-top: 20%;
%指定ではなく実数値で実装しましょう。
余白に関して言えば、余白が見栄えに大きな影響を与えない場合は、カンプ通りの実数値で問題は無いです。

htmlをみると、l-container と p-hero 間に余白が必要で、その2つは親子要素です。margin と padding の使い分けを意識しましょう

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +@use "../../Foundation/mixin" as *;
scss/Foundation/globalを見ると、mixin と variable を読み込んでいます。
これは、各ファイルで読み込みを2回行わないように、先に一つのファイルにまとめ、その一つのファイルのみを読み込めば良いようにしているものです。
global だけで動くはずなので、mixin の読み込みは削除しましょう

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +    background-color: white;
真っ白(カラーコードFFF)は変数で指定されているので、そちらを利用して記述しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +    margin-right: 0;
margin-left: auto;
で左から押し付けるような実装になるので、右の余白が無いという指定は不要です。
デベロッパーツールで、ここに数字を入れてみるなどして、どういう挙動になるか試してみてください。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +    background-color: white;
変数

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  &__btn {
カンプでは高さが50pxになっているので実装の仕方を変更しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +@use "../../Foundation/mixin" as *;
削除

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +  background-color: white;
変数

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    height: 70px;
高さがカンプ通りではないので調整してください。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    margin: auto 5%;
ここで距離が必要なのはロゴ画像とテキストの間のみです。
余白はロゴと隣接している左側のみにつけ、上下中央揃えになるような実装に変更しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    margin: auto 0;
こちらも上下中央揃えで対応しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +      display: none;
utilityクラスで、tab時、sp時は表示しないようにするクラスがあります。
クラスをあてて対応すると、htmlを見ただけで、sp時は表示されないということがわかるようになり、視認性が高まります。utilityクラスを探し、クラスを当てる方法で非表示にしてみましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +      // margin-right: 10px;
コメントアウトは意味のないものは消して提出しましょう。

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    padding: 10% 0;
高さ指定

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    width: 139px;
900近くのとき、ロゴと重ならないようにと考えての実装と想像は付きますが、
デザインカンプと違う実装を意味を持ってやるときにはコメントアウトを残すとレビュアーに対しては親切ですね！

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_hero.scss
> +@use "../../Foundation/mixin" as *;
削除

2022-10-18 13:32 UTC, oyuki-prog commented on assets/scss/Object/Project/_hero.scss
> +      font-size: 3vw;
画面幅375pxのとき3vwだと11.25pxになります。
基本的にはスマホであっても16px未満は小さくて読みづらいと考えて問題ないです。
そうならないよう、実数値で実装しましょう。

上記title部に関しても、同様に実数値で実装しましょう。

2022-10-18 17:08 UTC, yukodajima commented
FB項目を修正しました。
確認お願いします。

2022-10-18 23:45 UTC, oyuki-prog reviewed
FBしました。
修正をお願いします！

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Component/_btn.scss
> +  color: white;
ここも変数ですね

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +.p-article {
前回のレビュー時に指摘できていればよかったのですが、
今後、記事に関するページが追加される想定です。
そちらにp-article を使うとなると 記事でないコチラは articleという名前であるべきではないですね
p-serviceとかに変更しましょう！

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +    padding: 80px 0;
カンプ通りではないです。
p-article の上下の余白をカンプに揃えましょう。

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +  &__imgContainer--reverse {
modifierはelementsの軽微修正版です。
共通しているプロパティは一度のみ記述し、共通していない部分のみ&--reverseで足す形に変更しましょう。
参考リンク[https://qiita.com/masaki632d/items/0e6eb00e9d8611c4d8b7](url)

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_article.scss
> +      margin-left: auto;
pcファーストで記述する場合は、pcのスタイルはそのままtab,spにも当たるので、pcと重複するスタイルは記述しないようにしましょう。
ここ以外にも同様の問題点があれば修正をお願いします。

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    margin: auto 0;
display: flex があたっている場合は、余白による調整ではなく、
自動で子要素を計算して上下中央揃えにしてくれる書き方があるのでそちらに変更しましょう。

理由としては、ここは｢余白を取りたい部分｣というよりは｢上下中央揃え｣がしたい部分であるため、余白としての実装ではない方法を適用する形です。

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    margin: auto;
不要です

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    margin: auto 0 auto 10px;
下記4つの違いは認識しているでしょうか？
margin: 10px
margin: 10px 20px
margin: 10px 20px 30px
margin: 10px 20px 30px 40px

していなければ調べましょう。
ただ、こちらも上下中央揃えでいってほしい部分なので、実装はそちらでお願いします。

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_header.scss
> +    justify-content: space-between;
gapかspace-between
それぞれ役割が違い、どちらか一方で実装します。
違いを調べ、適切な方を残してください。

2022-10-18 23:45 UTC, oyuki-prog commented on assets/scss/Object/Project/_main.scss
> +    padding-top: 55px;
すみません60pxでお願いします。

2022-10-18 23:45 UTC, oyuki-prog commented on html/service.html
> +          <div id="c-humberger">
非表示用のマルチクラスはここにつけます！

2022-10-19 11:59 UTC, oyuki-prog commented
チェックしました。
マージして次のページの実装に移りましょう！

2022-10-19 11:59 UTC, oyuki-prog approved these changes

2022-10-19 11:59 UTC, merged