Top fukumoto
oyuki-prog/SuccessHoldingsTheme pull request #8
Opened 2022-10-15 14:51 UTC by sakifukumoto

スクロール部分はJSが必要になると思うので、
見た目のみ実装しています。
よろしくお願いします。

2022-10-16 03:36 UTC, sakifukumoto commented
デザインを修正しました。
よろしくお願いします。

2022-10-16 04:51 UTC, oyuki-prog commented
@sakifukumoto 
![スクリーンショット 2022-10-16 13 48 06](https://user-images.githubusercontent.com/89429515/196018647-5ce94085-6b36-4ed3-8cc5-d5fc4fecf236.png)
spサイズの事業紹介部分が、カンプと同じ高さになっていません。

![Top](https://user-images.githubusercontent.com/89429515/196018670-e118765f-2b8c-45de-bc38-3946a35e079b.png)
先程修正しようとしたheroイメージがコンテナ幅に収まっていません。

フッターがカンプと違うのは、宗さんとなにか確認があったのでしょうか？漏れですかね？

以上 見栄えについて3点確認をお願いします。

2022-10-16 06:37 UTC, sakifukumoto commented
見栄えの3点について修正しました。

2022-10-16 07:06 UTC, oyuki-prog commented
![Top](https://user-images.githubusercontent.com/89429515/196022845-a5be32cd-2fb1-4424-b98e-21bcc8048c4c.png)
まだヒーローの部分の左端がコンテナ幅にあってなさそうです。
サイズが1400pxより大きいときの表示崩れが無いかについても確認するようにしましょう。

導入企業のところのカードの枚数が4の倍数じゃない場合、写真のような形になります。
6枚とかだと不自然な余白がついてしまうので、6枚なら下の2枚は上のカードの真下になるようにしましょう。
□　□　□　□
□　□
↑↑
こういうイメージ

2022-10-16 08:13 UTC, sakifukumoto commented
hero,companyを修正しました。

2022-10-16 11:00 UTC, sakifukumoto commented
hero のimgを修正しました。

2022-10-16 11:26 UTC, oyuki-prog requested changes
FBしました。

余計なdivタグもなく、かなりきれいにコーディングできていると思います。
FBの他に一点要望で、p-footerに関する記述は_footer.scssに切り分けられています。
そのような実装が正解なので、
p-businessに関する記述は_bussiness.scss
p-worksに関する記述は_works.scss
のようにファイルの切り分けを行い、_index.scssに@use文を適宜追加してください！

2022-10-16 11:26 UTC, oyuki-prog commented on assets/scss/Object/Project/_top.scss
> +    height: 100px;
文量が増えたときにheightが絶対値指定になっていると文章がはみ出てしまいます。
基本的に文が増える可能性がある部分はheightのベタ打ちをしないくせをつけましょう。
それに伴って、SP,TAB表示で本文が2行以上になっても違和感が無いように調整してください

2022-10-16 11:26 UTC, oyuki-prog commented on assets/scss/Object/Project/_top.scss
> +    text-align: center;
文量を増やすと違和感があると思うので、試してみて修正しましょう

2022-10-16 11:26 UTC, oyuki-prog commented on assets/scss/Object/Project/_top.scss
> +  &__wrapper {
背景色をつけたいだけで、何かを囲んでいるわけではないので、wrapperではない名前に変更しましょう。

2022-10-16 12:46 UTC, sakifukumoto commented
レビュー修正しました。

2022-10-16 13:03 UTC, oyuki-prog reviewed
もう3点追加で修正をお願いします！

2022-10-16 13:03 UTC, oyuki-prog commented on assets/scss/Object/Project/_top.scss
> +
こちらの記述は_index.scss内にお願いします！
すでにexampleが入っていると思うので、それに習って
`@use "aboutUs"`
のような形で追加していきましょう

余計な空白行が多いので、一番下1つのみ(7行目まで)にしましょう

2022-10-16 13:03 UTC, oyuki-prog commented on assets/scss/style.scss
> +@forward "Object/Project/top";
1つめの指摘どおりにすると、ここはいじらなくても反映されるはずなので、ここの記述は削除しましょう。

2022-10-16 13:03 UTC, oyuki-prog commented on assets/scss/Object/Project/_work.scss
> +    position: relative;
幅が1100pxのあたりで、カードの距離がほぼ0になっています
余白を担保するような実装に変更をお願いします。

ここのファイル名ですが、p-worksに関わる記述なので、ファイル名も_works.scssでお願いします！

2022-10-16 13:23 UTC, sakifukumoto commented
3点のレビューを行いました。

2022-10-16 13:58 UTC, oyuki-prog reviewed
おそらくこれがラストになるはず！

2022-10-16 13:58 UTC, oyuki-prog commented on assets/scss/Object/Project/_aboutUs.scss
> +    font-size:min(3vw,42px);
font-sizeの指定が2個あります。
ここのフォントサイズはカンプでは28pxになっているのでカンプに合わせましょう

2022-10-16 13:58 UTC, oyuki-prog commented on html/top.html
> +              <ul class="p-footer__listBox">
｢組織コンサル｣が6文字なせいで、周りの余白より余計に余白がついています。
5つの余白が同じ幅になるように工夫してみましょう！

2022-10-16 14:03 UTC, oyuki-prog reviewed
ごめんなさいもう2つ追加で！

2022-10-16 14:03 UTC, oyuki-prog commented on assets/scss/Object/Project/_business.scss
> +    padding: 10%;
このあたりの余白はデザイナーが意味があってつけてる場合が多いので、実数値でコーディングしましょう

2022-10-16 14:03 UTC, oyuki-prog commented on assets/scss/Object/Project/_aboutUs.scss
> +    height: 300px;
一応カンプでみると斜め線が3枚の写真に被ってるので、ちょっと調整してカンプに近づけましょう。

2022-10-16 16:08 UTC, sakifukumoto commented
遅くなりすみません。
修正を行いました。

2022-10-16 21:49 UTC, oyuki-prog approved these changes

2022-10-17 09:24 UTC, oyuki-prog commented
大丈夫そうです！
マージってもっちゃんさんの方でできますかね？

2022-10-17 09:28 UTC, sakifukumoto commented
![FireShot Capture 001 - Top fukumoto by sakifukumoto · Pull Request #8 · oyuki-prog_SuccessHo_ - github com](https://user-images.githubusercontent.com/93373002/196141911-4908b20a-36e6-48b7-bb8f-7ca97e47867c.png)

こうなってます！
ここのプルリクですかね？

2022-10-17 09:43 UTC, oyuki-prog commented
そこですね！マージしてみてください！

2022-10-17 10:17 UTC, merged

2022-10-17 10:17 UTC, sakifukumoto commented
マージしました！
ブランチ削除のボタンがでてきました！

2022-10-17 10:20 UTC, oyuki-prog commented
削除してOKです!

2022-10-17 10:23 UTC, sakifukumoto commented
おゆきさん！すみません。
_top.scssってなにも書かなくてよかったんでしたっけ？
保存できてなかったみたいで、まだ残ってるかもしれません。